name: dave
favicon: null
layout_spectrum: 0.98843
typography_spectrum: 0.49997
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c9c9c9'
    - '#000000'
    - '#e30009'
    - '#da4e53'
    - '#393939'
  brandStrength: 0.5
  lightness: 0.04166843253187835
  saturation: 0.4663968156091869
  rhythmicContrast: 0.26267083222046494
purpose: []
